### ISSUE TITLE
change declaration format

### ISSUE THREAD

**Issue by ddouglascarr** [ddouglascarr/rooset#12]
Currently, delaration properties are expressed as '$type'. This needs to be change to something like

```
id:
  type: uuid
  description: Issue Id
  nullable: true
  foo: bar
```
