### ISSUE TITLE
ratk test declarations: reference and export preconditions

### ISSUE THREAD

**Issue by ddouglascarr** [ddouglascarr/rooset#16]
Turns out #5 was a terrible idea. Made everything a mess.

Better way is to allow refrencing of the 'given' parameter (precondition) of each scenario. Both within a test declaration file and from outside. (one test declaration can import a scenario from another). This will also allow referencing those scenarios in saga integration tests. 

Todo:
- rebase #5  
- allow "given" to be a string in one of these formats:
  - "#/new-unit-created" : for referencing the given of another scenario in this file
  - "UNIT_AGGREGATE_TESTS/new-unit-created" : for referencing the given of another scenario
- add "testType" prop to test file declaration
  - enum "COMMAND_INTEGRATION_TEST", "HTTP_REQUEST_INTEGRATION_TEST"
- have getTests take the testType enum and filter test declarations that way.
- Allow getTests to take an ALL enum to return all tests (for getting all preconditions).
- Have getTests inject the preconditions referenced above
- getTests should GLOB test-dir/**/*.yaml
- Test Decl schema should be as below (To allow for proper gherkin-style logs)
  - label, key should be optional for all (getTests should generate if missing)
  - the given key is used for looking up when importing scenario
  - Add preconditions prop to allow for declaring them at the top. Look there first and export them
Example test decl:

```
---
label: Unit Aggregate Tests
testType: COMMAND_INTEGRATION_TEST

preconditions:
  -
    label: Member granted permission
    key: member-permission-granted
    precondition: [ ... ]

scenarios:
  -
    label: Unit creator can grant privileges
    given: 
      key: unit-created
      label: Unit has been created
      precondition: [ ... ]
    when:
      label: Grant Privilege Command
      action: { ... }
    then: 
      label: Privilege Granted
      outcome: { ... }

  - 
    scenario: Non-privileged member cannot grant privileges
      given: #/unit-created
      when:
        action: { ... }
      then: 
        outcome: { .. }
```
